version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Necesario para que Nginx pueda hacer proxy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - CONTACT_RECEIVER=${CONTACT_RECEIVER}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
