version: '3'

services:
  frontend:
    build:
      context: ./frontend  # Carpeta del frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend  # Carpeta del backend
      dockerfile: Dockerfile
    # ports:  # Comentado para que solo sea accesible internamente
    #   - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules  # Evita sobreescribir node_modules
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
